### ISSUE TITLE
Rename Versions.csv to ClientVersions.csv and add ServerVersions.csv

### ISSUE THREAD

**Issue by Bluscream** [ReSpeak/tsdeclarations#20]
... to validate server versions clientside.

**Comment by Splamy** [comment]
There are no server version signatures?!

**Comment by Bluscream** [comment]
Yes, but there are patterns and i would like to check the version returned by the server against a list of existing server versions. Currently im only checking for a regex pattern which could also have non-existant versions

**Comment by Flakebi** [comment]
But what would you do if you encounter an unknown version?
There is no point in validating server versions. Also there is no point in validating client versions, it’s just that TeamSpeak expects a signature for them and there are limited signatures publicly available, so we have a list o them.

**Comment by Bluscream** [comment]
> But what would you do if you encounter an unknown version?

I would have a confirmation dialog if i (or the user) really want's to connect.

> There is no point in validating server versions. Also there is no point in validating client versions, it’s just that TeamSpeak expects a signature for them and there are limited signatures publicly available, so we have a list o them.

There is always a point in validating stuff that should not differ from other stuff

**Comment by Bluscream** [comment]
Can we still have that renamed? I would try to maintain the list

**Comment by Bluscream** [comment]
Yes, i'll try my best

**Comment by Gogosoft** [comment]
Gamescom 2018 player (BJCFQBU53C)

**Comment by Splamy** [comment]
Thanks, will add it
