### ISSUE TITLE
A1 & A2 explanation

### ISSUE THREAD

**Issue by CCCoderDE** [ReSpeak/tsdeclarations#22]
Hey guys,
first of all thank you for your amazing work on this project!

I'm currently trying to write a TS3Server implementation, but i'm stuck in the Init-Phase... After Sending Packet 3 of the Handshake, the client doesn't respond any more. I'm pretty sure is has something to do with me sending an empty (all zeroes) A1* byte-array...

Unfortunately, your protocol-document doesnt specify, what exactly should come from the server in this step... Could you tell me, what the server has to send as A1* and A2*?

*A1 and A2 are the names from the byte-arrays as you named them in the following document:
[Link to explanation in ts3protocol.md](https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md#22-packet-1-client---server)

**Comment by CCCoderDE** [comment]
BTW I'm from Germany as well, so a German explanation would also work for me 😄

**Comment by Splamy** [comment]
We do not want to go into the details of the server as teamspeak is not quite fond seeing such stuff. The paper is intentionally written focused on the interoperability from the client side.
Regarding your question, (I haven't checked it), but the client should just accept any random content within this field. You might want recheck your actual packet structure and make sure there are now mistakes.
Furthermore the client should resend his handshake packet if he thinks it was lost or broken.

**Comment by CCCoderDE** [comment]
The Client correctly responds to the first packet from the Server, which tells me, the connection and packet structure itself should be correct...

**Comment by CCCoderDE** [comment]
And yes, the Client starts the handshake one more time, but it gets stuck on the same packet

**Comment by CCCoderDE** [comment]
Maybe I rephrase my question... if I want to write a TS3Client, what do I need the data in A1/A2 for? How should I interpret the received Data?

**Comment by Splamy** [comment]
The client knows nothing about A1 and A2. As you can see from the paper he doesn't even process them in any way and A2 is encrypted by the server to transport some protected state.
Also I just checked, all clients can from 3.0.0 to 3.1.9 handle zeroed A1,2 just fine.
As a tip, check than your `level` in packet 3 has a reasonable size, otherwise the client will hang in an endless loop.

**Comment by CCCoderDE** [comment]
Alright, trank you :)
