### ISSUE TITLE
ANNOUNCEMENT

### ISSUE THREAD

**Issue by Splamy** [ReSpeak/tsdeclarations#36]
We will drop the 'channel' column from the [Versions.csv](https://github.com/ReSpeak/tsdeclarations/blob/master/Versions.csv) as it is not really maintainable.
The master will be updated on 11.02.19

**Comment by Bluscream** [comment]
> maintainale
maintainable

**Comment by Bluscream** [comment]
hm?

**Comment by Splamy** [comment]
es gab noch keine neue version die der server pushen konnte

**Comment by Bluscream** [comment]
achso :D
