### ISSUE TITLE
TS5 Version Sign?

### ISSUE THREAD

**Issue by BerndSchmecka** [ReSpeak/tsdeclarations#37]
How do you get those Version Hashes? Can you please find one for "5.0.0-alpha216 [Build: 1556918526] on Windows"?

**Comment by BerndSchmecka** [comment]
btw the Build Date of 5.0.0-alpha216 is 03.05.2019 23:22:06 if it matters

**Comment by Bluscream** [comment]
`sWDezOByhJ2GNjO5+w3oGWpI9jXXZy72iBSdSryHBMVCW3c7khfLzmpipqC/3yUACQU07yEwThcYLsK4+UYrAw==`

**Comment by BerndSchmecka** [comment]
Thank You very much

**Comment by Flakebi** [comment]
New Versions have been added in 57e972e
