### ISSUE TITLE
Update Badges.csv

### ISSUE THREAD

**Issue by MarkL4YG** [ReSpeak/tsdeclarations#38]
The badges list could use an update. YaTQA has a good [list on the available badges](https://yat.qa/ressourcen/abzeichen-badges/) which seems to be up to date.

**Comment by Bluscream** [comment]
Of course it seems up to date because i maintain it smh :D

**Comment by Bluscream** [comment]
Also check out https://minopia.de/ts it has a badges.json

**Comment by MarkL4YG** [comment]
``Valentim's Day 2019``, ``TS5 Beta Competition Winner`` and ``TeamSpeak Merch Owner - 2nd Edition`` are missing in the CSV.

**Comment by MarkL4YG** [comment]
> Also check out https://minopia.de/ts it has a badges.json 

That's great! Is it allowed to directly query the JSON file or shall I copy it to any project that needs it?

**Comment by Bluscream** [comment]
Depends on how often you access it

**Comment by MarkL4YG** [comment]
> 
> 
> Depends on how often you access it

Thinking about querying it once per start-up of an application that may potentially be delivered to other communities too. So, I guess I'll cache it on our servers and refresh once per day if you have worries about the load?

**Comment by Splamy** [comment]
Blu, if I give you access to this repo, would you keep the badges up to date?

**Comment by Bluscream** [comment]
@Splamy well, I could run a python script using a github lib, sure

**Comment by MarkL4YG** [comment]
Hey @Bluscream ,  
I tried proxying your json ressource using nginx caching and it appears CloudFlare doesn't like that.  
Would you mind adding our server to your IP whitelist in the CF access rules so I do not have to manually implement caching? 🙂

**Comment by Bluscream** [comment]
```php
<?php
	header('Content-Type: application/json');
	$url = "list.json";
	$cache_file = "badges.json.cache";
	if(file_exists($cache_file)) {
	  if(time() - filemtime($cache_file) > 600) {
		 $cache = file_get_contents($url);
		 file_put_contents($cache_file, $cache);
	  }
	} else {
	  $cache = file_get_contents($url);
	  file_put_contents($cache_file, $cache);
	}
	$content = file_get_contents($cache_file);
	echo $content;
?>
```

That should be simple enough

**Comment by Splamy** [comment]
Why not just update and maintain *this* repo file, then you can access the [Badges.csv](https://raw.githubusercontent.com/ReSpeak/tsdeclarations/master/Badges.csv) directly without limits...

**Comment by MarkL4YG** [comment]
@Bluscream I would bet CF would also catch this as the whole purpose is to have only legitimate browsers access the site. I also agree with @Splamy that maintaining the repository is a better alternative as this more publicly accessible and GitHub deals with the traffic.

**Comment by Splamy** [comment]
Kay, I added an automatic badge scraper to my webserver; the latest badge file will be hourly downloaded and parsed for new badges.
