### ISSUE TITLE
How to have hash version ?

### ISSUE THREAD

**Issue by Edith445544986** [ReSpeak/tsdeclarations#39]
Hi ! I would like to know how you have the hash version ?

**Comment by Flakebi** [comment]
Hi, you can get the hash or signature of a version in several ways. For example it is stored in the client binaries. You also get the signature for versions of other clients in the `clientinfo` command so a client or serverquery can request the version signature of other clients on a server. This is how we get this info.

**Comment by Edith445544986** [comment]
But for version 5.0.0-alpha? Did you do it the same way ?

**Comment by Flakebi** [comment]
Yes

**Comment by Edith445544986** [comment]
OK thanks for your answer :)
