### ISSUE TITLE
No 'clientinit'-respond

### ISSUE THREAD

**Issue by friedelschoen** [ReSpeak/tsdeclarations#61]
Hello dear Team,

I'm using TS3 Server v3.13.3 and 'Client-Version' 3.5.7.

So far, I passed the low-handshake and sent 'clientivinit' and got a response (acknowledged). 'clientinit' will not get acknowledged. I think I got a problem calculating the sharedIV and Mac, I imported the public keys from the licenses as Ed25519 Point and I imported the whole block without key-type (block-pub-key, license-block-type, valid-before/after and content) as `int.from_bytes(clamp(sha512(block[1..])[..32]), endian=big)` after that I use the pub-key and multiplied it with the block-int + parent (root key/resulting key before). I generated the sharedSecret of my private key and that point as Ed25519 pub-key. I tried everything but nothing works :( It would be great if anyone can help me.

Here my code python-code:

```python
def compute_iv_mac(ls: List['License'], private: bytes, alpha: bytes, beta: bytes) -> Tuple[bytes, bytes]:
key = b'\xcd\r\xe2\xae\xd4cEP\x9a~<\xfd\x8fh\xb3\xdcuU\xb2\x9d\xcc\xecs\xcd\x18u\x0f\x998\x12@\x8a'

for l in ls:
	parent = Ed25519.decode_point(key)
	
	priv = int.from_bytes(clamp(bytes(sha512(l.block[1:]).digest()[:32])), 'big')

	key = Ed25519.encode_point(l.public_key * priv + parent)

temp_iv = sha512(PrivateKey.load(private).do_exchange(PublicKey(key))[:32]).digest()

iv  = xor_bytes(temp_iv[:10], alpha) + xor_bytes(temp_iv[10:], beta)
mac = sha1(iv).digest()[:8]

return iv, mac
```

**Comment by Flakebi** [comment]
Hi,

I don’t see anything wrong with the code you posted.
We have a testcase that might be helpful, you can compare your results with the results here:
https://github.com/ReSpeak/tsclientlib/blob/4d08aaa77e94ec385b562e48310d270722adf517/tsproto/src/algorithms.rs#L317-L397
