### ISSUE TITLE
Which tools did you use for reversing the ts3 protocol

### ISSUE THREAD

**Issue by Mandofskii** [ReSpeak/tsdeclarations#65]

**Comment by Flakebi** [comment]
[Ghidra](https://github.com/NationalSecurityAgency/ghidra) is a helpful tool for reverse engineering.

**Comment by alom4hdi** [comment]
@Flakebi You used just Ghidra ? If not can you name the others please.
I want to reverse engineer a protocol that I have server and client binary of it, but IDK where should I start to looking for in binary file, can you help me please ?
someone recommended me to start looking for xrefs to network system calls, like bind(), recv(), accept() and...

**Comment by alom4hdi** [comment]
sorry?

**Comment by Flakebi** [comment]
I used Ghidra and wireshark.
