### ISSUE TITLE
ot=1 parameter in `clientinitiv` missing from the protocol docs

### ISSUE THREAD

**Issue by zumoshi** [ReSpeak/tsdeclarations#66]
Hello,
Thanks for the comprehensive document on the protocol. However while inspecting the official client with wireshark I noticed it sends an extra parameter on `clientinitiv` command (section 3.1) which is not listed in the docs.

ReSpeak also seems to send this parameter:
https://github.com/ReSpeak/tsclientlib/blob/5d0ee951bfbe3a5c0137a697bd53b35e0f2096fc/utils/tsproto-packets/src/packets.rs#L1081

Is there any explanation on what it does or can it be missing? should it be added to the protocol doc?

**Comment by Flakebi** [comment]
Thanks, I added it to the documentation. Better late than never :)
